
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package default_package;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.4
 * 2022-12-13T22:14:52.081Z
 * Generated source version: 3.5.4
 *
 */

@javax.jws.WebService(
                      serviceName = "project_utility_service",
                      portName = "project_utility_port",
                      targetNamespace = "http://default_package/",
                      wsdlLocation = "http://localhost:8080/project_rmi4/services/project_utility_port?wsdl",
                      endpointInterface = "default_package.ProjectUtility")

public class Project_Utility_PortImpl implements ProjectUtility {

    private static final Logger LOG = Logger.getLogger(Project_Utility_PortImpl.class.getName());

    /* (non-Javadoc)
     * @see default_package.ProjectUtility#listarMesas(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String listarMesas(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation listarMesas");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-603087389";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.ProjectUtility#reservar(int arg0, int arg1, java.lang.String arg2, java.lang.String arg3)*
     */
    public java.lang.String reservar(int arg0, int arg1, java.lang.String arg2, java.lang.String arg3) {
        LOG.info("Executing operation reservar");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            java.lang.String _return = "_return292270757";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.ProjectUtility#cancelar(int arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3)*
     */
    public java.lang.String cancelar(int arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) {
        LOG.info("Executing operation cancelar");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            java.lang.String _return = "_return-1082941469";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
