
package default_package;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.4
 * 2022-12-13T22:14:51.950Z
 * Generated source version: 3.5.4
 *
 */
public final class ProjectUtility_ProjectUtilityPort_Client {

    private static final QName SERVICE_NAME = new QName("http://default_package/", "ProjectUtilityService");

    private ProjectUtility_ProjectUtilityPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProjectUtilityService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ProjectUtilityService ss = new ProjectUtilityService(wsdlURL, SERVICE_NAME);
        ProjectUtility port = ss.getProjectUtilityPort();

        {
        System.out.println("Invoking listarMesas...");
        java.lang.String _listarMesas_arg0 = "_listarMesas_arg0747618935";
        java.lang.String _listarMesas_arg1 = "_listarMesas_arg11664391458";
        java.lang.String _listarMesas__return = port.listarMesas(_listarMesas_arg0, _listarMesas_arg1);
        System.out.println("listarMesas.result=" + _listarMesas__return);


        }
        {
        System.out.println("Invoking reservar...");
        int _reservar_arg0 = 1217660526;
        int _reservar_arg1 = -2051578034;
        java.lang.String _reservar_arg2 = "_reservar_arg21568386014";
        java.lang.String _reservar_arg3 = "_reservar_arg3-1219719815";
        java.lang.String _reservar__return = port.reservar(_reservar_arg0, _reservar_arg1, _reservar_arg2, _reservar_arg3);
        System.out.println("reservar.result=" + _reservar__return);


        }
        {
        System.out.println("Invoking cancelar...");
        int _cancelar_arg0 = 651445459;
        java.lang.String _cancelar_arg1 = "_cancelar_arg1-1025129533";
        java.lang.String _cancelar_arg2 = "_cancelar_arg22953147";
        java.lang.String _cancelar_arg3 = "_cancelar_arg31215557137";
        java.lang.String _cancelar__return = port.cancelar(_cancelar_arg0, _cancelar_arg1, _cancelar_arg2, _cancelar_arg3);
        System.out.println("cancelar.result=" + _cancelar__return);


        }

        System.exit(0);
    }

}
