package default_package;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.4
 * 2022-12-13T22:14:52.111Z
 * Generated source version: 3.5.4
 *
 */
@WebServiceClient(name = "project_utility_service",
                  wsdlLocation = "http://localhost:8080/project_rmi4/services/project_utility_port?wsdl",
                  targetNamespace = "http://default_package/")
public class ProjectUtilityService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://default_package/", "ProjectUtilityService");
    public final static QName ProjectUtilityPort = new QName("http://default_package/", "ProjectUtilityPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/project_rmi3/services/ProjectUtilityPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProjectUtilityService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/project_rmi3/services/ProjectUtilityPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProjectUtilityService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProjectUtilityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProjectUtilityService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ProjectUtilityService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProjectUtilityService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProjectUtilityService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ProjectUtility
     */
    @WebEndpoint(name = "project_utility_port")
    public ProjectUtility getProjectUtilityPort() {
        return super.getPort(ProjectUtilityPort, ProjectUtility.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProjectUtility
     */
    @WebEndpoint(name = "project_utility_port")
    public ProjectUtility getProjectUtilityPort(WebServiceFeature... features) {
        return super.getPort(ProjectUtilityPort, ProjectUtility.class, features);
    }

}
